#!/bin/bash
# A simple calc app
# By Nikolay Komolov
# https://github.com/nkspb

add() {
  answer=$(($1 + $2))
}

sub() {
  answer=$(($1 - $2))
}

mult() {
  answer=$(($1 * $2))
}

div() {
  answer=$(($1 / $2))
}

[[ $# -lt 3 ]] && \
  echo "Usage: a|s|m|d num1 num2"

[[ $1 != a ]] && [[ $1 != s ]] && [[ $1 != m ]] && [[ $1 != d ]] && \
  echo "Wrong operation. Must be a|s|m|d"

if [[ $1 == a ]]; then add $2 $3
elif [[ $1 == s ]]; then sub $2 $3
elif [[ $1 == d ]]; then div $2 $3
elif [[ $1 == m ]]; then mult $2 $3
fi

echo $answer
exit 0
