#!/bin/bash

# image_batch_resize
# Resize images in a folder
# by Nikolay Komolov 2018
# https://github.com/nkspb

folder=$1
width=$2
height=$3
dest=$4 || "./resized_images/"

# Attempt to cd to folder
cd $folder || { echo "Folder is inaccesible or doesn't exists" >&2; exit 1; }

for file in *; do
  # Check if $file is a regular file
  if [[ -f $file ]]; then
    # Check if $file is an image
    if file "$file" | grep -qE 'image|bitmap'; then
      # Resize the image
      new_dest=$dest\/res_${file}
      echo $new_dest
      # convert $file -resize $2x$3 $dest\/res_${file}
    fi
  fi
done

exit 0
